version: '3.8'

services:
  app:
    build: .
    container_name: springboot-app
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://c23-86-webapp-callcenter-nocountry.b.aivencloud.com:14364/defaultdb?useSSL=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: avnadmin
      SPRING_DATASOURCE_PASSWORD: AVNS_MDsQWSiEuB9jbvaV6zh
    ports:
      - "8080:8080"
